name: Build Falcon Dart

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, x86]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Create build folder
        run: mkdir -p build

      - name: Compile Falcon Dart
        run: |
          echo "Compiling falcon.dart for ${{ matrix.os }}-${{ matrix.arch }}..."
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            dart compile exe falcon/falcon.dart -o build/falcon-${{ matrix.os }}-${{ matrix.arch }}.exe
          else
            dart compile exe falcon/falcon.dart -o build/falcon-${{ matrix.os }}-${{ matrix.arch }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: falcon-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: build/
